### ISSUE TITLE
🚧 Implement result and error handling when it is standardized

### ISSUE THREAD

**Issue by heikomat** [process-engine/consumer_api_core#1]
#### Describe your issue

We currently have concepts about the way to handle results and errors with express, but they are not implemented yet.

As soon as we have defined how we handle results and errors with express, we need to update the consumer_api_router accordingly.

UPDATE: Error handling will be implemented through
- https://github.com/essential-projects/http_node/pull/2 and
- https://github.com/essential-projects/errors.ts/pull/1

#### How can others reproduce the issue?

When you send a request to the consumer_api, it gets accepted, but it is never answered

#### Possible solution

Define how results and errors should be handled with express, and update the consumer_api_router accordingly.

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by 5ebastianMeier** [comment]
The PRs mentioned have been merged.

We should be able to update the consumer_api_router now.

**Comment by ElRaptorus** [comment]
@5ebastianMeier @heikomat Is this still an issue?

**Comment by ElRaptorus** [comment]
This has been done. 
See:
https://github.com/process-engine/consumer_api_http/blob/develop/src/consumer_api_controller.ts
https://github.com/process-engine/consumer_api_client/blob/develop/src/consumer_api_client_service.ts
