### ISSUE TITLE
✅ Add tests for the consumer-api

### ISSUE THREAD

**Issue by heikomat** [process-engine/consumer_api_core#2]
#### Describe your issue

We need to add integration-tests for the consumer-api. For the first step, it's enough if the consumer-api answeres with mock-data for that.

#### Possible solution

Add integration-tests for the functionality mentioned in the consumer-api-concept

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by ElRaptorus** [comment]
I think this can be closed.
Any objections @heikomat @5ebastianMeier @cmg-dev ?

**Comment by heikomat** [comment]
@ElRaptorus You're correct
