### ISSUE TITLE
Attempting to finish an already finished user tasks results in 403 - Forbidden error

### ISSUE THREAD

**Issue by robpal94** [process-engine/consumer_api_core#21]
#### Describe your issue

If you call the method `finishUserTask()` for the same user task twice, you'll get the following error:

```
403 - Access to process model forbidden
```

It should be:
```
404 - User Task not found
```

#### How can others reproduce the issue?
* Create a process with a user task
* Try to finish this user task twice

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by ElRaptorus** [comment]
https://github.com/process-engine-pro/organization/issues/72

**Comment by ElRaptorus** [comment]
This is not a bug with the consumer api. The error is most likely within the user task handler of the process engine itself.
