### ISSUE TITLE
Inconsistent property naming

### ISSUE THREAD

**Issue by ElRaptorus** [process-engine/consumer_api_core#24]
#### Describe your issue

There are some interfaces, which use snake-casing for some or all of their properties instead of camelCase.
This should be corrected in the contracts-package and in this package afterwards.

See: https://github.com/process-engine/consumer_api_contracts/issues/15

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by ElRaptorus** [comment]
https://github.com/process-engine-pro/organization/issues/132

**Comment by cmg-dev** [comment]
@ElRaptorus Please describe/reference the desired naming convention.

**Comment by ElRaptorus** [comment]
https://github.com/process-engine-pro/organization/issues/133

**Comment by ElRaptorus** [comment]
@cmg-dev I updated the comments.
