### ISSUE TITLE
Process Engine returns 404 instead of 403 if the user has no access rights to a sublane

### ISSUE THREAD

**Issue by robpal94** [process-engine/consumer_api_core#26]
#### Describe your issue
Consider the following process:
![test_consumer_api_sublane_process](https://user-images.githubusercontent.com/38498731/41239877-78fc2538-6d99-11e8-862b-23dc11d7c2bf.png)

If the user has no access to the sublane _Lane D_, the Consumer API returns the HTTP Error
```
404 - StartEvent_1 not found
```
 In my opinion, I would expect the process engine to throw something like this: 
```
403 - No Permissions to access StartEvent_1
```

#### How can others reproduce the issue?
* Create a process with a sublane
* Place a start event in this sublane
* Grand the executing user only access to the root lane
* Try to execute the process

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by ElRaptorus** [comment]
As far as I remember, the reason for this was to ensure that users, who don't have access to the given end event, should not even know that the event exists in the first place.
A 403 would reveal the existence of that event, a 404 does not.

Usually, you would be correct that 403 is the expected error code for this, though.

/cc @cmg-dev @moellenbeck
