### ISSUE TITLE
🤡 Mock the consumer-api-service

### ISSUE THREAD

**Issue by heikomat** [process-engine/consumer_api_core#3]
#### Describe your issue

The consumer-api-service is currently just a shell that implements its interface, but has no real implementation, not even mock-implementation. As a first step, we need to mock the service so that we can implement integration-tests (see #2)

#### How can others reproduce the issue?

The consumer-api won't throw errors on incorrect input and doesn't even resolve with data that makes any sense

#### Possible solution

Add mocked consumer-api-service functionality

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by ElRaptorus** [comment]
I think this can be closed.
Any objections @heikomat @5ebastianMeier @cmg-dev ?
