### ISSUE TITLE
Implement accessibility checks based on new object model

### ISSUE THREAD

**Issue by 5ebastianMeier** [process-engine/consumer_api_core#34]
#### Describe your issue

During the clean up of the `ProcessEngineAdapter`, the accessibility checks have been removed.

We should clarify who is responsible for checking those rights.

The new persistance layer provides two access points for retrieving data:
* FlowNodeInstancePersistance
* ProcessModelPersistance

The data that can be queried by both of these, might be partially protected. The decision of what is treated as protected and unprotected is modeled in the BPMN diagram.

I don't think that each API (ConsumerAPI, ManagementAPI, ...) should implement the claim checks for accessing the data model itself, because that would result in repetative code and is prone to errors.

#### Possible solution

Instead of directly using the `FlowNodeInstancePersistance` and `ProcessModelPersistance` to query for persisted items, I'd rather use a service per persistance implementation to perform the claim checks.

For example this can filter a process model that is queried right before any other logic from the ConsumerAPI accesses it.

This has the advantage that the ConsumerAPI only has to implement additional claim checks that result from its functional API. The same goes for the Management API, that is likely to introduce even more specific use cases on top of things modeled in the BPMN diagram (e.g. deployment).

#### Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by ElRaptorus** [comment]
https://github.com/process-engine-pro/organization/issues/171

**Comment by ElRaptorus** [comment]
Since we've agreed that the process engine itself is responsible for handling Auth-related checks, this issue is closed in favour of https://github.com/process-engine/process_engine/issues/108
