### ISSUE TITLE
🐛token.current does not Work after Parallel Gateways

### ISSUE THREAD

**Issue by cmg-dev** [process-engine/consumer_api_core#76]
## Describe your issue

I discovered, that we can not use the the `token.current` after a parallel path.

I tried to render the output of a ScriptTask, in the UserTask that followed the ScriptTask:

![ui_test](https://user-images.githubusercontent.com/4034128/49588568-59e61a00-f967-11e8-80cb-33996c2a7e2c.png)

1. The Access via `${token.current.a}` does not work.
1. The Access via `${token.history.FlowNodeInstanceName}` does work.

The access via the history, will work.

## How can others reproduce the issue?

Execute this Process:

1. not working current variant:

   [ui_test_broken.bpmn.zip](https://github.com/process-engine/consumer_api_core/files/2653328/ui_test_broken.bpmn.zip)

1. working History variant:

   [ui_test.bpmn.zip](https://github.com/process-engine/consumer_api_core/files/2653308/ui_test.bpmn.zip)

## Possible solution

Correct the `getOldtokenFormat()`.

## Issue checklist

Please check the boxes in this list after submitting your Issue:

- [x] I've checked if this issue already exists
- [x] I've included all the information that i think is relevant
- [x] I've added logs and/or screenshots (if applicable)
- [x] I've mentioned PRs and issues that relate to this one

**Comment by cmg-dev** [comment]
@ElRaptorus @Paulomart 

I just updated a non-working variant of the process.

**Comment by ElRaptorus** [comment]
@cmg-dev Please place such issues in the runtime.
This isn't even related to the consumer api.

I moved the issue here: https://github.com/process-engine/process_engine_runtime/issues/180

/cc @Paulomart

**Comment by Paulomart** [comment]
Next time you can just move the issue: 
<img width="199" alt="grafik" src="https://user-images.githubusercontent.com/4148404/49632935-cb6da900-f9f7-11e8-8ff4-a2ca56a46451.png">

**Comment by ElRaptorus** [comment]
@Paulomart good to know.
